# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# variables:
#   rgname: $(rgname)
#   vaultname: $(vaultname)

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Private Account wahid2272'
    KeyVaultName: 'TF-Key-Vault-72'
    SecretsFilter: '*'
    RunAsPreJob: false



# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Private Account wahid2272'
#     scriptType: 'ps'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       $sshPublicKey = (Get-AzKeyVaultSecret -VaultName 'YourLibraryVariableGroup' -Name 'sshPublicKey').SecretValueText
#       $env:SSH_PUBLIC_KEY = $sshPublicKey

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Private Account wahid2272'
    backendAzureRmResourceGroupName: 'aks-terraform'
    backendAzureRmStorageAccountName: 'akstfstore72'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'tf/terraform.tfstate'
    
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-var "APP_ID=$(spn-id)" -var"CLIENT_SECRET=$(spn-secret)"'
    environmentServiceNameAzureRM: 'Private Account wahid2272'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-var "APP_ID=$(spn-id)" -var"CLIENT_SECRET=$(spn-secret)"'
    environmentServiceNameAzureRM: 'Private Account wahid2272'
