name: TERRAFORM

on:
  push:
    branches: [ main ]
    paths: 
    - 'terraform/**'

  workflow_dispatch:
jobs:
  terraforms:
    runs-on: ubuntu-latest

    env:
      APP_ID: $({ secters.APP_ID })
      CLIENT_SECRET: $({ secrets.CLIENT_SECTER })
      STORAGE_KEY: $({ secrets.STORAGE_KEY})
      ARM_RG_NAME: $({ secrets.ARM_RG_NAME })
      ARM_CONTAINER_NAME: $({ secrets.ARM_CONTAINER_NAME })
      ARM_STORAGE_ACCOUNT_NAME: $({ secrets.ARM_STORAGE_ACCOUNT_NAME })

    defaults:
      run:
        working-directory: ./terraform
      
    steps:
      - uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name{{ env.ARM_RG_NAME }}" -backend-config="storage_account_name{{ env.ARM_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name{{ env.ARM_CONTAINER_NAME }}" -backend-config="key{{ env.STORAGE_KEY }}"
      
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
