name: TERRAFORM

on:
  push:
    branches: [ main ]
    paths: 
    - 'terraform/**'

  workflow_dispatch:
jobs:
  terraforms:
    runs-on: ubuntu-latest

    env:
      APP_ID: ${{ secrets.APP_ID }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECTER }}
      STORAGE_KEY: ${{ secrets.STORAGE_KEY}}
      RG_NAME: ${{ secrets.RG_NAME }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}

    defaults:
      run:
        working-directory: ./terraform
      
    steps:
      - uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        # env:
        #   STORAGE_KEY: $({ secrets.STORAGE_KEY})
        #   ARM_RG_NAME: $({ secrets.ARM_RG_NAME })
        #   ARM_CONTAINER_NAME: $({ secrets.ARM_CONTAINER_NAME })
        #   ARM_STORAGE_ACCOUNT_NAME: $({ secrets.ARM_STORAGE_ACCOUNT_NAME })
        run: terraform init -backend-config="resource_group_name=$RG_NAME" -backend-config="storage_account_name=$STORAGE_ACCOUNT_NAME" -backend-config="container_name=$CONTAINER_NAME" -backend-config="key=$STORAGE_KEY"
      
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
